# Generated by Django 4.2 on 2024-01-01
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_code", models.CharField(max_length=32, unique=True, verbose_name="任务单号")),
                ("user_id", models.CharField(max_length=32, verbose_name="用户工号")),
                ("user_name", models.CharField(max_length=64, verbose_name="姓名")),
                ("department", models.CharField(blank=True, max_length=128, verbose_name="部门")),
                ("copies", models.PositiveIntegerField(default=1, verbose_name="复印份数")),
                ("description", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "待取号"),
                            ("queued", "排队中"),
                            ("in_progress", "处理中"),
                            ("completed", "完成"),
                            ("delivered", "已交付"),
                        ],
                        default="waiting",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("urgent", models.BooleanField(default=False, verbose_name="加急")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("printed_at", models.DateTimeField(blank=True, null=True, verbose_name="标签打印时间")),
                ("start_time", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finish_time", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("delivered_at", models.DateTimeField(blank=True, null=True, verbose_name="交付时间")),
            ],
            options={
                "ordering": ["urgent", "created_at"],
                "verbose_name": "复印任务",
                "verbose_name_plural": "复印任务",
            },
        ),
        migrations.CreateModel(
            name="TaskEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "待取号"),
                            ("queued", "排队中"),
                            ("in_progress", "处理中"),
                            ("completed", "完成"),
                            ("delivered", "已交付"),
                        ],
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="备注")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="时间")),
                ("operator", models.CharField(blank=True, max_length=64, verbose_name="操作员")),
                (
                    "task",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="tasks.task"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "任务事件",
                "verbose_name_plural": "任务事件",
            },
        ),
    ]
